apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
  - name: client
    port: 2181
  - name: server
    port: 2888
  - name: leader-election
    port: 3888
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: zookeeper
        image: aiacs-docker-virtual.docker.oraclecorp.com/ai-zookeeper-noha:3.4.6
        imagePullPolicy: IfNotPresent
        ports:
        - name: client
          containerPort: 2181
        - name: server
          containerPort: 2888
        - name: leader-election
          containerPort: 3888
        volumeMounts:
        - name: zookeeper-vol
          mountPath: /data
        resources:
          requests:
            memory: 256Mi
        env:
        - name: JVMFLAGS
          value: -Xms205m -Xmx205m
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-vol
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: hostpath
      resources:
        requests:
          storage: 256Mi
